language: java
jdk:
  - openjdk7
  - oraclejdk7
install:
  - gem install bundler
  - bundle install
  - echo "yes" | sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update
  - sudo apt-get install libgeos-dev libproj-dev postgresql-9.1-postgis
  - sudo apt-get install -qq libgeos++-dev
script: buildr clean package
